name: Context-Aware RAG with Groq & LLaMA-3

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-rag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install sentence-transformers pypdf faiss-cpu langchain_huggingface

      - name: Run the RAG Script
        run: python rag_llama3_pdf_qa.py
