name: RAG with Groq and LLaMA-3

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pypdf sentence-transformers faiss-cpu langchain langchain-community langchain-groq

      - name: Run RAG PDF QA Script
        run: |
          python rag_llama3_pdf_qa.py
